resources:
  repositories:
  - repository:  self 
queue:
  name: Hosted VS2017
variables:
  versionSuffixForPre: 'pre-$(Build.BuildNumber)'
  versionSuffixForProd: 'prod-$(Build.BuildNumber)'
  csprojPath: 'src/firstwebapp/**.*csproj'

steps:
- task: DotNetCoreInstaller@0
  inputs:
    packageType: 'sdk'
    version: '2.2.105' 

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: '$(csprojPath)'
    restoreDirectory: 'Destination dotNET'


- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: build
    configuration: 'release'
    projects: '$(csprojPath)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'drop' 
    publishLocation: 'container'